CRUD/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("student.urls"))
]

student/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("",views.show,name="show"),
    path("add/",views.adddata,name="add"),
    path("update/<int:id>",views.updatedata,name="update"),
    path("delete/<int:id>",views.deletedata,name="delete"),
     path('search_student', views.searchstudent, name='searchstudent'),
]

student/models.py
from django.db import models

MY_CHOICES = [
        ("CE", 'CE'),
        ("EXTC", 'EXTC'),
        ("ME", 'ME'),
        ("AI", 'AI'),
        ("IT", 'IT'),
    ]


class Student(models.Model):
    fname=models.CharField(max_length=25)
    lname=models.CharField(max_length=25)
    email=models.EmailField(max_length=25)
    phone=models.PositiveIntegerField()
    branch=models.CharField(max_length=50,choices=MY_CHOICES)

    def __str__(self):
        return self.fname

student/forms.py
from django import forms
from .models import Student

class StudentRegistration(forms.ModelForm):
    class Meta:
        model = Student
        fields = "__all__"
        labels = {'fname': "First Name", 'lname': "Last Name", 'phone': "Phone no"}
        widgets = {
            'fname': forms.TextInput(attrs={"class": "form-control"}),
            'lname': forms.TextInput(attrs={"class": "form-control"}),
            'email': forms.EmailInput(attrs={"class": "form-control"}),
            'phone': forms.NumberInput(attrs={"class": "form-control"}),
            'branch': forms.Select(attrs={"class": "form-control"}),
        }

student/views.py
from django.shortcuts import render,HttpResponseRedirect
from .models import Student, MY_CHOICES
from .forms import StudentRegistration
from django.db.models import Q


def show (request):
    student=Student.objects.all()
    return render (request, "crudapp/show.html",{'student':student})



def adddata(request):
    if request.method == "POST":
        fm=StudentRegistration(request.POST)
        if fm.is_valid():
            fm.save()
            return HttpResponseRedirect("/")
    else:
        fm=StudentRegistration()
    return render (request,"crudapp/adddata.html",{'form':fm})



def updatedata(request ,id):
    if request.method=="POST":
        student=Student.objects.get(pk=id)
        fm=StudentRegistration(request.POST,instance=student)
        if fm.is_valid():
            fm.save()
        return HttpResponseRedirect("/")
    else:
        student=Student.objects.get(pk=id)
        fm=StudentRegistration(instance=student)
    return render (request, "crudapp/update.html",{'form':fm})


def deletedata(request ,id):
    if request.method=="POST":
        student=Student.objects.get(pk=id)
        student.delete()
        return HttpResponseRedirect("/")


def searchstudent(request):
    if request.method == 'POST':
        n1 = request.POST.get('output')
        print(n1)
        student = Student.objects.all()
        std = None  # Initialize the variable
        if n1:
            std = student.filter(
                Q(fname__icontains=n1) |
                Q(lname__icontains=n1) |
                Q(email__icontains=n1) |
                Q(phone__icontains=n1) |
                Q(branch__icontains=n1)
            )
            print( std.count())
        return render(request, "crudapp/show.html", {'student': std})
    else:
        return HttpResponse('An Exception Occurred')

student/templates/crudapp/adddata.html
{% extends "crudapp/base.html" %}

{% block content1 %}

    <div clas="row ">
        <div class="col-6 offset-3">
            <form action="" method="post" novalidate >
                {% csrf_token %}
                {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                <span class='errorstyle'>{{error}}</span>
                {% endfor %}
                {% endif %}
                <br>

                {% for field in form %}
                  {{field.label_tag}}
                  {{field}}
                  <div>
                    {% for error in field.errors %}
                      <small class="errorstyle">{{error|striptags}}</small>
                    {% endfor %}
                </div>
                {% endfor %}
                <input type="submit" class="btn btn-success mt-3 ">
            <a href="{% url 'show' %}" class=" btn btn-success mt-3"> Back to All students</a>
            </form>



</div>
</div>

{% endblock content1 %}

student/templates/crudapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %} CRUD {% endblock title %}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />

   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">

    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    {% include "crudapp/navbar.html" %}
    <div class="container">
        {% block content1 %} {% endblock content1 %}
    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossorigin="anonymous"
    ></script>

    <!-- Bootstrap JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

  </body>
</html>

student/templates/crudapp/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark">
  <div class="container-fluid ">
      <a class="navbar-brand ms-5 " style="padding-right:240px;" href="/">Student Management</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
          aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
              <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="/">All_Students</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url "add" %}">Add_Students</a>
              </li>
          </ul>
      </div>
      <form action="{% url 'searchstudent' %}" method="post" class="d-flex">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="output">
        <button class="btn btn-success" type="submit">Search</button>
    </form>

  </div>
</nav>

student/templates/crudapp/show.html
{% extends "crudapp\base.html" %}


{% block content1 %}
{% if student  %}
<table  class="table table-hover mt-3">
    <tr>
        <th> ID</th>
        <th> First Name </th>
        <th> Last Name</th>
        <th> Email Id</th>
        <th> Phone</th>
        <th> Branch</th>
        <th> Action</th>
    </tr>

    {%  for st in student %}

    <tr>
        <td> {{st.id}} </td>
        <td> {{st.fname}} </td>
        <td> {{st.lname}} </td>
        <td> {{st.email}} </td>
        <td> {{st.phone}} </td>
        <td> {{ st.get_branch_display }} </td>
        {% comment %} #get_branch_display is a method provided by Django for model choice fields that returns the human-readable name of the field. {% endcomment %}
        <td>

            <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#viewModal{{st.id}}">
                <i class="fa-solid fa-circle-info"></i> View
            </button>

              <!-- Modal -->
              <div class="modal fade" id="viewModal{{st.id}}" tabindex="-1" role="dialog" aria-labelledby="viewModalLabel{{st.id}}" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="viewModalLabel{{st.id}}">Student:{{st.fname}} {{st.lname}} </h5>

                        </div>
                        <div class="modal-body">
                            <ul style="list-style-type:none;">
                                <li>Student id : <strong> {{st.id}} </strong></li>
                                <li>Student First Name : <strong> {{st.fname}} </strong></li>
                                <li>Student Last Name : <strong>  {{st.lname}}</strong></li>
                                <li>Student email id : <strong> {{st.email}} </strong></li>
                                <li>Student phone no : <strong> {{st.phone}} </strong></li>
                                <li>Student Branch : <strong> {{ st.get_branch_display }} </strong></li>

                            </ul>


                        </div>
                        <div class="modal-footer">
                            <button type="button"class="btn btn-primary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>




            <a href="{% url 'update' st.id %}" class="btn btn-warning btn-sm">
                <i class="fa-regular fa-pen-to-square"></i> Edit
            </a>
            <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteModal{{st.id}}">
                <i class="fa-solid fa-trash"></i> Delete
            </button>

            <!-- Modal -->
            <div class="modal fade" id="deleteModal{{st.id}}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel{{st.id}}" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="deleteModalLabel{{st.id}}">Confirm Deletion</h5>

                        </div>
                        <div class="modal-body">
                            <p>Are you sure you want to delete the student?</p>
                        </div>
                        <div class="modal-footer">
                            <form action="{% url 'delete' st.id %}" method="post" class="d-inline">
                                {% csrf_token %}
                                <input type="submit" value="Delete" class="btn btn-danger">
                            </form>
                            <button type="button" class="btn btn-primary" data-dismiss="modal">No</button>
                        </div>
                    </div>
                </div>
            </div>



        </td>

    </tr>
    {% endfor %}

    </table>

    {% else %}
    <h1 class="bg-primary mt-5  text-center "> No data</h1>
    {% endif %}

{% endblock content1 %}

student/templates/crudapp/update.html
{% extends "crudapp/base.html" %}

{% block content1 %}

    <div clas="row ">
        <div class="col-6 offset-3">
            <form action="" method="post" novalidate >
                {% csrf_token %}
                {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                <span class='errorstyle'>{{error}}</span>
                {% endfor %}
                {% endif %}
                <br>

                {% for field in form %}
                  {{field.label_tag}}
                  {{field}}
                  <div>
                    {% for error in field.errors %}
                      <small class="errorstyle">{{error|striptags}}</small>
                    {% endfor %}
                </div>
                {% endfor %}
                <input type="submit" class="btn btn-success mt-3 ">
            <a href="{% url 'show' %}" class=" btn btn-success mt-3"> Back to All students</a>
            </form>



</div>
</div>

{% endblock content1 %}